name: notes_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  firebase_admin: ^0.2.0
<<<<<<< HEAD
  get_it: ^7.6.9
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
=======
>>>>>>> parent of a64c4e5 (fcm)
  mailer: ^6.1.0
  serverpod: 1.2.6

dev_dependencies:
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
